on: [push]

jobs:
  dorametrix:
    runs-on: ubuntu-latest
    name: Dorametrix
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push image to Docker Hub
        uses: docker/build-push-action@v2
        with:
          context: ./
          tags: mikaelvesavuori/dorametrix-pipe:1.0.0
          push: ${{ github.ref == 'refs/heads/main' }}